substitutions:
  devicename: base
  friendly: Base Device
  board: esp32-c3-devkitm-1
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  fallback_ap_password: !secret wifi_password
  ld_uart_tx: GPIO21
  ld_uart_rx: GPIO20
  ld_baud: "256000"

esphome:
  name: ${devicename}
  friendly_name: ${friendly}
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: ${board}
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: ${api_key}

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${friendly} Fallback"
    password: ${fallback_ap_password}

captive_portal:

uart:
  id: uart_bus
  tx_pin: ${ld_uart_tx}
  rx_pin: ${ld_uart_rx}
  baud_rate: ${ld_baud}

ld2410:
  uart_id: uart_bus

binary_sensor:
  - platform: ld2410
    has_target:
      name: "${friendly} Target Detected"

sensor:
  - platform: ld2410
    detection_distance:
      name: "${friendly} Detection Distance"
