substitutions:
  devicename: base
  board: esp32-c3-devkitm-1
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  fallback_ap_password: !secret wifi_password
  ld_uart_tx: GPIO21
  ld_uart_rx: GPIO20
  ld_baud: "256000"

esphome:
  name: ${devicename}
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: ${board}
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret ha_api_key

# Bluetooth Proxy
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 300ms
    active: true

bluetooth_proxy:
  active: true

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${devicename} Fallback"
    password: ${fallback_ap_password}

captive_portal:

uart:
  id: uart_bus
  tx_pin: ${ld_uart_tx}
  rx_pin: ${ld_uart_rx}
  baud_rate: ${ld_baud}

ld2410:
  uart_id: uart_bus

binary_sensor:
  - platform: ld2410
    has_target:
      name: "Target Detected"

sensor:
  - platform: ld2410
    detection_distance:
      name: "Detection Distance"

  # Diagnostic sensors
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    update_interval: 60s

  - platform: internal_temperature
    name: "Internal Temperature"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"

  - platform: version
    name: "ESPHome Version"

button:
  - platform: restart
    name: "Restart"

  - platform: safe_mode
    name: "Safe Mode"
